### ISSUE TITLE
Commit e62234a removed NSFW section

### ISSUE THREAD

**Issue by Steven-park** [fmhy/bookmarks#2]
For some reason the lines 4418-4553 have been removed, was this intentional?

If so can we get a seperate html with the NSFW included from now on?

https://github.com/fmhy/bookmarks/commit/e62234a41f1fdc254416368ee4e88aaa9846b9c5

**Comment by nbats** [comment]
yeah it was on purpose we no longer host the nsfw version on our site or github but you can still view it on rentry
